language: python
python: 3.6
node_js: 10
script:
- echo "DO NOTHING"
jobs:
  include:
    - stage: docker staging
      python: '3.6'
      if: branch = master
      script:
        - npm install
        - npm run travis-deploy-once "npm run semantic-release"
        - docker build -t allovince/yinxing.crawler .
        - docker tag allovince/yinxing.crawler allovince/yinxing.crawler:staging
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/yinxing.crawler:staging;
    - stage: docker release
      python: '3.6'
      if: tag IS present
      script:
        - docker build -t allovince/yinxing.crawler .
        - docker tag allovince/yinxing.crawler allovince/yinxing.crawler:$TRAVIS_TAG
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/yinxing.crawler:latest;
        - docker push allovince/yinxing.crawler:$TRAVIS_TAG;
